/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useEffect, useRef } from "react";
import { useGLTF } from "@react-three/drei";

export default function SceneModel({ ...props }) {
  const group = useRef();
  const { nodes, materials } = useGLTF("/models/Carte collectionable.gltf");

  useEffect(() => {
    console.log("");
  }, []);

  return (
    <group ref={group} {...props} dispose={null} position={[0, 0, 0]}>
      <mesh
        geometry={nodes.Support.geometry}
        material={materials.Verre}
        position={[0, 0.5, 0]}
        receiveShadow={true}
        castShadow={true}
      >
        <group position={[0, 1.6, -0.06]}>
          <mesh
            geometry={nodes.Plane001.geometry}
            material={materials.Image2}
            receiveShadow={true}
            castShadow={true}
          />
          <mesh
            geometry={nodes.Plane001_1.geometry}
            material={materials["Matériau carte"]}
            receiveShadow={true}
            castShadow={true}
          />
        </group>
        <group position={[0, 1.6, 0.01]}>
          <mesh
            geometry={nodes.Plane003.geometry}
            material={materials.Image1}
            receiveShadow={true}
            material-color={"white"}
            castShadow={true}
          />
          <mesh
            geometry={nodes.Plane003_1.geometry}
            material={materials["Matériau carte"]}
            receiveShadow={true}
            castShadow={true}
          />
        </group>
      </mesh>
      <group position={[0, 0.14, 0]}>
        <mesh
          geometry={nodes.Cylinder001.geometry}
          material={materials.Podium}
          // material-color={"blue"}
          receiveShadow={true}
          // castShadow={true}
        />
        <mesh
          geometry={nodes.Cylinder001_1.geometry}
          material={materials.Verre}
          receiveShadow={true}
          material-color={"white"}
          castShadow={true}
        />
      </group>
    </group>
  );
}

useGLTF.preload("/models/Carte collectionable.gltf");
