/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useEffect, useRef } from "react";
import { useGLTF, useTexture } from "@react-three/drei";
import { useFrame } from "@react-three/fiber";
import { Vector2 } from "three";

export default function SceneModel({
  frontImage = "/images/carousel/1.jpg",
  backImage = "/images/carousel/2.jpg",
  podiumColor,
}) {
  const group = useRef();
  const image1Mesh = useRef();
  const image2Mesh = useRef();
  const { nodes, materials } = useGLTF("/models/Carte collectionable.gltf");

  const [texture1, texture2] = useTexture([frontImage, backImage]);

  // useFrame((state) => {
  //   group.current.rotation.y += 0.005;
  // });

  useEffect(() => {
    texture1.center = new Vector2(0.5, 0.5);
    texture1.rotation = Math.PI;
    texture1.flipY = false;

    texture2.center = new Vector2(0.5, 0.5);
    texture2.rotation = Math.PI;
    texture2.flipY = false;
  }, []);

  useEffect(() => {
    image1Mesh.current.material.map = texture1;
    image1Mesh.current.material.map.flipY = false;

    image2Mesh.current.material.map = texture2;
    image2Mesh.current.material.map.flipY = false;
  }, [image1Mesh, image2Mesh]);

  return (
    <group ref={group} dispose={null} position={[0, -1.5, 0]}>
      <mesh
        geometry={nodes.Support.geometry}
        material={materials.Verre}
        position={[0, 0.5, 0]}
        receiveShadow={true}
        castShadow={true}
      >
        <group position={[0, 1.6, -0.06]}>
          <mesh
            ref={image2Mesh}
            geometry={nodes.Plane001.geometry}
            material={materials.Image2}
            receiveShadow={true}
            castShadow={true}
          />
          <mesh
            geometry={nodes.Plane001_1.geometry}
            material={materials["Matériau carte"]}
            receiveShadow={true}
            castShadow={true}
          />
        </group>
        <group position={[0, 1.6, 0.01]}>
          <mesh
            ref={image1Mesh}
            geometry={nodes.Plane003.geometry}
            material={materials.Image1}
            receiveShadow={true}
            material-color={"white"}
            castShadow={true}
          />
          <mesh
            geometry={nodes.Plane003_1.geometry}
            material={materials["Matériau carte"]}
            receiveShadow={true}
            castShadow={true}
          />
        </group>
      </mesh>
      <group position={[0, 0.14, 0]}>
        <mesh
          geometry={nodes.Cylinder001.geometry}
          material={materials.Podium}
          material-color={podiumColor}
          receiveShadow={true}
        />
        <mesh
          geometry={nodes.Cylinder001_1.geometry}
          material={materials.Verre}
          receiveShadow={true}
          material-color={"white"}
          castShadow={true}
        />
      </group>
    </group>
  );
}

useGLTF.preload("/models/Carte collectionable.gltf");
